/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortaalRouteImport } from './routes/portaal'
import { Route as KwaliteitRouteImport } from './routes/kwaliteit'
import { Route as AanmeldenRouteImport } from './routes/aanmelden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDCodeRouteImport } from './routes/api/public/d.$code'

const PortaalRoute = PortaalRouteImport.update({
  id: '/portaal',
  path: '/portaal',
  getParentRoute: () => rootRouteImport,
} as any)
const KwaliteitRoute = KwaliteitRouteImport.update({
  id: '/kwaliteit',
  path: '/kwaliteit',
  getParentRoute: () => rootRouteImport,
} as any)
const AanmeldenRoute = AanmeldenRouteImport.update({
  id: '/aanmelden',
  path: '/aanmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDCodeRoute = ApiPublicDCodeRouteImport.update({
  id: '/api/public/d/$code',
  path: '/api/public/d/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/kwaliteit': typeof KwaliteitRoute
  '/portaal': typeof PortaalRoute
  '/api/public/d/$code': typeof ApiPublicDCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/kwaliteit': typeof KwaliteitRoute
  '/portaal': typeof PortaalRoute
  '/api/public/d/$code': typeof ApiPublicDCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/kwaliteit': typeof KwaliteitRoute
  '/portaal': typeof PortaalRoute
  '/api/public/d/$code': typeof ApiPublicDCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanmelden'
    | '/kwaliteit'
    | '/portaal'
    | '/api/public/d/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aanmelden' | '/kwaliteit' | '/portaal' | '/api/public/d/$code'
  id:
    | '__root__'
    | '/'
    | '/aanmelden'
    | '/kwaliteit'
    | '/portaal'
    | '/api/public/d/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanmeldenRoute: typeof AanmeldenRoute
  KwaliteitRoute: typeof KwaliteitRoute
  PortaalRoute: typeof PortaalRoute
  ApiPublicDCodeRoute: typeof ApiPublicDCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portaal': {
      id: '/portaal'
      path: '/portaal'
      fullPath: '/portaal'
      preLoaderRoute: typeof PortaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kwaliteit': {
      id: '/kwaliteit'
      path: '/kwaliteit'
      fullPath: '/kwaliteit'
      preLoaderRoute: typeof KwaliteitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanmelden': {
      id: '/aanmelden'
      path: '/aanmelden'
      fullPath: '/aanmelden'
      preLoaderRoute: typeof AanmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/d/$code': {
      id: '/api/public/d/$code'
      path: '/api/public/d/$code'
      fullPath: '/api/public/d/$code'
      preLoaderRoute: typeof ApiPublicDCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanmeldenRoute: AanmeldenRoute,
  KwaliteitRoute: KwaliteitRoute,
  PortaalRoute: PortaalRoute,
  ApiPublicDCodeRoute: ApiPublicDCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
